#!/bin/bash 
[[ -f ~/.Xresources ]] && xrdb -merge -I$HOME ~/.Xresources

exec xset -dpms -s off & # Desable back screen after 10 minutes
exec ck-launch-session dbus-launch --sh-syntax --exit-with-session awesome >> ~/.awesome_stdout 2 >> ~/.awesome_stderr
